#!/bin/bash
sudo ./cmds/clean-all
sudo mkdir -p ./build/nemesis/vrf
sudo cp -f ./transactions/* ./build/nemesis/vrf
docker-compose -f cmds/bootstrap/docker-compose.yml up --remove-orphans $1 setup-network
