#!/bin/bash

build_flag="--build"
daemon_flag=

while [ "$1" != "" ]; do
    case $1 in
        -d | --daemon )         daemon_flag="-d"
                                ;;
        -b | --build )          build_flag="--build"
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
sudo ./cmds/clean-all
sudo mkdir -p ./build/nemesis/vrf
sudo cp -f ./transactions/* ./build/nemesis/vrf
docker rm -f $(docker ps -aq)
docker-compose -f cmds/bootstrap/docker-compose.yml up $daemon_flag $build_flag
